#!/bin/bash -e

# $1: Full Path to Package
# $2: Full Path to target installation directory: /Applications
# $3: Mountpoint of installation disk: / or /Volumes/External_Drive
# $4: Root directory of currently booted system

# Set up a 'cypherpunk' group on the machine, which will be used to exempt Cypherpunk's own traffic from the killswitch
GROUP=cypherpunk
if ! dscl . read /Groups/$GROUP ; then
	# Find an available group id
	GID=$(dscl . -list /Groups PrimaryGroupID | awk '{g[$2]=1}END{for(i=333;i<500;i++)if(!g[i]){print i;exit 0}exit 1}')
	# Create group
	dscl . -create /Groups/$GROUP gid $GID
	# Add 'everyone' to the group as a nested group, otherwise users will not be able to run binaries
	# with +setgid owned by the cypherpunk group (this does not affect everyone's traffic)
	dseditgroup -o edit -a everyone -t group $GROUP
fi

# Update permissions on the client executable to exempt it from the killswitch
chgrp $GROUP "/Applications/Cypherpunk Privacy.app/Contents/MacOS/Cypherpunk Privacy"

# (The daemon does not need +setgid since it's running as root and can do it by itself)

# Make sure the daemon is running in the background
launchctl load /Library/LaunchDaemons/com.cypherpunk.privacy.service.plist

# Launch the client
osascript -e 'tell application "Cypherpunk Privacy" to activate'
