#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          cypherpunk
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Cypherpunk Privacy
# Description:       Cypherpunk Privacy background daemon
### END INIT INFO

# Author: Cypherpunk Privacy <support@cypherpunk.com>

DESC="Cypherpunk Privacy"
DAEMON=/usr/local/cypherpunk/bin/cypherpunk-privacy-service
